import PlusnewAbstractElement from '../PlusnewAbstractElement';
import { htmlElement } from './dom/htmlElement';
import { linkElement } from './dom/linkElement';
import { metaElement } from './dom/metaElement';
import { styleElement } from './dom/styleElement';
import { titleElement } from './dom/titleElement';
import { bodyElement } from './dom/bodyElement';
import { headElement } from './dom/headElement';
import { addressElement } from './dom/addressElement';
import { articleElement } from './dom/articleElement';
import { asideElement } from './dom/asideElement';
import { footerElement } from './dom/footerElement';
import { headerElement } from './dom/headerElement';
import { h1Element } from './dom/h1Element';
import { h2Element } from './dom/h2Element';
import { h3Element } from './dom/h3Element';
import { h4Element } from './dom/h4Element';
import { h5Element } from './dom/h5Element';
import { h6Element } from './dom/h6Element';
import { hgroupElement } from './dom/hgroupElement';
import { mainElement } from './dom/mainElement';
import { navElement } from './dom/navElement';
import { sectionElement } from './dom/sectionElement';
import { blockquoteElement } from './dom/blockquoteElement';
import { ddElement } from './dom/ddElement';
import { dirElement } from './dom/dirElement';
import { divElement } from './dom/divElement';
import { dlElement } from './dom/dlElement';
import { dtElement } from './dom/dtElement';
import { figcaptionElement } from './dom/figcaptionElement';
import { figureElement } from './dom/figureElement';
import { hrElement } from './dom/hrElement';
import { liElement } from './dom/liElement';
import { olElement } from './dom/olElement';
import { pElement } from './dom/pElement';
import { preElement } from './dom/preElement';
import { ulElement } from './dom/ulElement';
import { aElement } from './dom/aElement';
import { abbrElement } from './dom/abbrElement';
import { bElement } from './dom/bElement';
import { bdiElement } from './dom/bdiElement';
import { bdoElement } from './dom/bdoElement';
import { brElement } from './dom/brElement';
import { citeElement } from './dom/citeElement';
import { codeElement } from './dom/codeElement';
import { dataElement } from './dom/dataElement';
import { dfnElement } from './dom/dfnElement';
import { emElement } from './dom/emElement';
import { iElement } from './dom/iElement';
import { kbdElement } from './dom/kbdElement';
import { markElement } from './dom/markElement';
import { qElement } from './dom/qElement';
import { rbElement } from './dom/rbElement';
import { rpElement } from './dom/rpElement';
import { rtElement } from './dom/rtElement';
import { rtcElement } from './dom/rtcElement';
import { rubyElement } from './dom/rubyElement';
import { sElement } from './dom/sElement';
import { sampElement } from './dom/sampElement';
import { smallElement } from './dom/smallElement';
import { spanElement } from './dom/spanElement';
import { strongElement } from './dom/strongElement';
import { subElement } from './dom/subElement';
import { supElement } from './dom/supElement';
import { timeElement } from './dom/timeElement';
import { ttElement } from './dom/ttElement';
import { uElement } from './dom/uElement';
import { varElement } from './dom/varElement';
import { wbrElement } from './dom/wbrElement';
import { areaElement } from './dom/areaElement';
import { audioElement } from './dom/audioElement';
import { imgElement } from './dom/imgElement';
import { mapElement } from './dom/mapElement';
import { trackElement } from './dom/trackElement';
import { videoElement } from './dom/videoElement';
import { appletElement } from './dom/appletElement';
import { embedElement } from './dom/embedElement';
import { iframeElement } from './dom/iframeElement';
import { noembedElement } from './dom/noembedElement';
import { objectElement } from './dom/objectElement';
import { paramElement } from './dom/paramElement';
import { pictureElement } from './dom/pictureElement';
import { sourceElement } from './dom/sourceElement';
import { canvasElement } from './dom/canvasElement';
import { noscriptElement } from './dom/noscriptElement';
import { scriptElement } from './dom/scriptElement';
import { delElement } from './dom/delElement';
import { insElement } from './dom/insElement';
import { captionElement } from './dom/captionElement';
import { colElement } from './dom/colElement';
import { colgroupElement } from './dom/colgroupElement';
import { tableElement } from './dom/tableElement';
import { tbodyElement } from './dom/tbodyElement';
import { tdElement } from './dom/tdElement';
import { tfootElement } from './dom/tfootElement';
import { thElement } from './dom/thElement';
import { theadElement } from './dom/theadElement';
import { trElement } from './dom/trElement';
import { buttonElement } from './dom/buttonElement';
import { datalistElement } from './dom/datalistElement';
import { fieldsetElement } from './dom/fieldsetElement';
import { formElement } from './dom/formElement';
import { inputElement } from './dom/inputElement';
import { labelElement } from './dom/labelElement';
import { legendElement } from './dom/legendElement';
import { meterElement } from './dom/meterElement';
import { optgroupElement } from './dom/optgroupElement';
import { optionElement } from './dom/optionElement';
import { outputElement } from './dom/outputElement';
import { progressElement } from './dom/progressElement';
import { selectElement } from './dom/selectElement';
import { textareaElement } from './dom/textareaElement';
import { detailsElement } from './dom/detailsElement';
import { dialogElement } from './dom/dialogElement';
import { menuElement } from './dom/menuElement';
import { menuitemElement } from './dom/menuitemElement';
import { summaryElement } from './dom/summaryElement';
import { contentElement } from './dom/contentElement';
import { elementElement } from './dom/elementElement';
import { shadowElement } from './dom/shadowElement';
import { slotElement } from './dom/slotElement';
import { templateElement } from './dom/templateElement';
import { altGlyphElement } from './dom/altGlyphElement';
import { altGlyphDefElement } from './dom/altGlyphDefElement';
import { altGlyphItemElement } from './dom/altGlyphItemElement';
import { animateElement } from './dom/animateElement';
import { animateColorElement } from './dom/animateColorElement';
import { animateMotionElement } from './dom/animateMotionElement';
import { animateTransformElement } from './dom/animateTransformElement';
import { circleElement } from './dom/circleElement';
import { clipPathElement } from './dom/clipPathElement';
import { colorprofileElement } from './dom/colorprofileElement';
import { cursorElement } from './dom/cursorElement';
import { defsElement } from './dom/defsElement';
import { descElement } from './dom/descElement';
import { ellipseElement } from './dom/ellipseElement';
import { feBlendElement } from './dom/feBlendElement';
import { feColorMatrixElement } from './dom/feColorMatrixElement';
import { feComponentTransferElement } from './dom/feComponentTransferElement';
import { feCompositeElement } from './dom/feCompositeElement';
import { feConvolveMatrixElement } from './dom/feConvolveMatrixElement';
import { feDiffuseLightingElement } from './dom/feDiffuseLightingElement';
import { feDisplacementMapElement } from './dom/feDisplacementMapElement';
import { feDistantLightElement } from './dom/feDistantLightElement';
import { feFloodElement } from './dom/feFloodElement';
import { feFuncAElement } from './dom/feFuncAElement';
import { feFuncBElement } from './dom/feFuncBElement';
import { feFuncGElement } from './dom/feFuncGElement';
import { feFuncRElement } from './dom/feFuncRElement';
import { feGaussianBlurElement } from './dom/feGaussianBlurElement';
import { feImageElement } from './dom/feImageElement';
import { feMergeElement } from './dom/feMergeElement';
import { feMergeNodeElement } from './dom/feMergeNodeElement';
import { feMorphologyElement } from './dom/feMorphologyElement';
import { feOffsetElement } from './dom/feOffsetElement';
import { fePointLightElement } from './dom/fePointLightElement';
import { feSpecularLightingElement } from './dom/feSpecularLightingElement';
import { feSpotLightElement } from './dom/feSpotLightElement';
import { feTileElement } from './dom/feTileElement';
import { feTurbulenceElement } from './dom/feTurbulenceElement';
import { filterElement } from './dom/filterElement';
import { fontElement } from './dom/fontElement';
import { fontfaceElement } from './dom/fontfaceElement';
import { fontfaceFormatElement } from './dom/fontfaceFormatElement';
import { fontfaceNameElement } from './dom/fontfaceNameElement';
import { fontfaceSrcElement } from './dom/fontfaceSrcElement';
import { fontfaceUriElement } from './dom/fontfaceUriElement';
import { foreignObjectElement } from './dom/foreignObjectElement';
import { gElement } from './dom/gElement';
import { glyphElement } from './dom/glyphElement';
import { glyphRefElement } from './dom/glyphRefElement';
import { hkernElement } from './dom/hkernElement';
import { imageElement } from './dom/imageElement';
import { lineElement } from './dom/lineElement';
import { linearGradientElement } from './dom/linearGradientElement';
import { markerElement } from './dom/markerElement';
import { maskElement } from './dom/maskElement';
import { metadataElement } from './dom/metadataElement';
import { missingglyphElement } from './dom/missingglyphElement';
import { mpathElement } from './dom/mpathElement';
import { pathElement } from './dom/pathElement';
import { patternElement } from './dom/patternElement';
import { polygonElement } from './dom/polygonElement';
import { polylineElement } from './dom/polylineElement';
import { radialGradientElement } from './dom/radialGradientElement';
import { rectElement } from './dom/rectElement';
import { setElement } from './dom/setElement';
import { stopElement } from './dom/stopElement';
import { svgElement } from './dom/svgElement';
import { switchElement } from './dom/switchElement';
import { symbolElement } from './dom/symbolElement';
import { textElement } from './dom/textElement';
import { textPathElement } from './dom/textPathElement';
import { trefElement } from './dom/trefElement';
import { tspanElement } from './dom/tspanElement';
import { useElement } from './dom/useElement';
import { viewElement } from './dom/viewElement';
import { vkernElement } from './dom/vkernElement';

declare global {
  namespace plusnew {
    namespace JSX {
      /**
       * the JSX.Element is a abstract representation of a Component
       */
      interface Element extends PlusnewAbstractElement {}

      interface ElementChildrenAttribute {
        // @FIXME children are always arrays, but typescript doesn't accept that because of react
        children: {};
      }

      /**
       * All the DOM Nodes are here
       */
      interface IntrinsicElements {
        html: htmlElement;
        link: linkElement;
        meta: metaElement;
        style: styleElement;
        title: titleElement;
        body: bodyElement;
        head: headElement;
        address: addressElement;
        article: articleElement;
        aside: asideElement;
        footer: footerElement;
        header: headerElement;
        h1: h1Element;
        h2: h2Element;
        h3: h3Element;
        h4: h4Element;
        h5: h5Element;
        h6: h6Element;
        hgroup: hgroupElement;
        main: mainElement;
        nav: navElement;
        section: sectionElement;
        blockquote: blockquoteElement;
        dd: ddElement;
        dir: dirElement;
        div: divElement;
        dl: dlElement;
        dt: dtElement;
        figcaption: figcaptionElement;
        figure: figureElement;
        hr: hrElement;
        li: liElement;
        ol: olElement;
        p: pElement;
        pre: preElement;
        ul: ulElement;
        a: aElement;
        abbr: abbrElement;
        b: bElement;
        bdi: bdiElement;
        bdo: bdoElement;
        br: brElement;
        cite: citeElement;
        code: codeElement;
        data: dataElement;
        dfn: dfnElement;
        em: emElement;
        i: iElement;
        kbd: kbdElement;
        mark: markElement;
        q: qElement;
        rb: rbElement;
        rp: rpElement;
        rt: rtElement;
        rtc: rtcElement;
        ruby: rubyElement;
        s: sElement;
        samp: sampElement;
        small: smallElement;
        span: spanElement;
        strong: strongElement;
        sub: subElement;
        sup: supElement;
        time: timeElement;
        tt: ttElement;
        u: uElement;
        var: varElement;
        wbr: wbrElement;
        area: areaElement;
        audio: audioElement;
        img: imgElement;
        map: mapElement;
        track: trackElement;
        video: videoElement;
        applet: appletElement;
        embed: embedElement;
        iframe: iframeElement;
        noembed: noembedElement;
        object: objectElement;
        param: paramElement;
        picture: pictureElement;
        source: sourceElement;
        canvas: canvasElement;
        noscript: noscriptElement;
        script: scriptElement;
        del: delElement;
        ins: insElement;
        caption: captionElement;
        col: colElement;
        colgroup: colgroupElement;
        table: tableElement;
        tbody: tbodyElement;
        td: tdElement;
        tfoot: tfootElement;
        th: thElement;
        thead: theadElement;
        tr: trElement;
        button: buttonElement;
        datalist: datalistElement;
        fieldset: fieldsetElement;
        form: formElement;
        input: inputElement;
        label: labelElement;
        legend: legendElement;
        meter: meterElement;
        optgroup: optgroupElement;
        option: optionElement;
        output: outputElement;
        progress: progressElement;
        select: selectElement;
        textarea: textareaElement;
        details: detailsElement;
        dialog: dialogElement;
        menu: menuElement;
        menuitem: menuitemElement;
        summary: summaryElement;
        content: contentElement;
        element: elementElement;
        shadow: shadowElement;
        slot: slotElement;
        template: templateElement;

        altGlyph: altGlyphElement;
        altGlyphDef: altGlyphDefElement;
        altGlyphItem: altGlyphItemElement;
        animate: animateElement;
        animateColor: animateColorElement;
        animateMotion: animateMotionElement;
        animateTransform: animateTransformElement;
        circle: circleElement;
        clipPath: clipPathElement;
        colorprofile: colorprofileElement;
        cursor: cursorElement;
        defs: defsElement;
        desc: descElement;
        ellipse: ellipseElement;
        feBlend: feBlendElement;
        feColorMatrix: feColorMatrixElement;
        feComponentTransfer: feComponentTransferElement;
        feComposite: feCompositeElement;
        feConvolveMatrix: feConvolveMatrixElement;
        feDiffuseLighting: feDiffuseLightingElement;
        feDisplacementMap: feDisplacementMapElement;
        feDistantLight: feDistantLightElement;
        feFlood: feFloodElement;
        feFuncA: feFuncAElement;
        feFuncB: feFuncBElement;
        feFuncG: feFuncGElement;
        feFuncR: feFuncRElement;
        feGaussianBlur: feGaussianBlurElement;
        feImage: feImageElement;
        feMerge: feMergeElement;
        feMergeNode: feMergeNodeElement;
        feMorphology: feMorphologyElement;
        feOffset: feOffsetElement;
        fePointLight: fePointLightElement;
        feSpecularLighting: feSpecularLightingElement;
        feSpotLight: feSpotLightElement;
        feTile: feTileElement;
        feTurbulence: feTurbulenceElement;
        filter: filterElement;
        font: fontElement;
        fontface: fontfaceElement;
        'fontface-format': fontfaceFormatElement;
        'fontface-name': fontfaceNameElement;
        'fontface-src': fontfaceSrcElement;
        'fontface-uri': fontfaceUriElement;
        foreignObject: foreignObjectElement;
        g: gElement;
        glyph: glyphElement;
        glyphRef: glyphRefElement;
        hkern: hkernElement;
        image: imageElement;
        line: lineElement;
        linearGradient: linearGradientElement;
        marker: markerElement;
        mask: maskElement;
        metadata: metadataElement;
        missingglyph: missingglyphElement;
        mpath: mpathElement;
        path: pathElement;
        pattern: patternElement;
        polygon: polygonElement;
        polyline: polylineElement;
        radialGradient: radialGradientElement;
        rect: rectElement;
        set: setElement;
        stop: stopElement;
        svg: svgElement;
        switch: switchElement;
        symbol: symbolElement;
        text: textElement;
        textPath: textPathElement;
        tref: trefElement;
        tspan: tspanElement;
        use: useElement;
        view: viewElement;
        vkern: vkernElement;
      }

      interface IntrinsicAttributes {
        key?: string | number;
      }
    }
  }
}
