import PlusnewAbstractElement from '../PlusnewAbstractElement';
import { htmlElement } from './dom/htmlElement';
import { linkElement } from './dom/linkElement';
import { metaElement } from './dom/metaElement';
import { styleElement } from './dom/styleElement';
import { titleElement } from './dom/titleElement';
import { bodyElement } from './dom/bodyElement';
import { headElement } from './dom/headElement';
import { addressElement } from './dom/addressElement';
import { articleElement } from './dom/articleElement';
import { asideElement } from './dom/asideElement';
import { footerElement } from './dom/footerElement';
import { headerElement } from './dom/headerElement';
import { h1Element } from './dom/h1Element';
import { h2Element } from './dom/h2Element';
import { h3Element } from './dom/h3Element';
import { h4Element } from './dom/h4Element';
import { h5Element } from './dom/h5Element';
import { h6Element } from './dom/h6Element';
import { hgroupElement } from './dom/hgroupElement';
import { mainElement } from './dom/mainElement';
import { navElement } from './dom/navElement';
import { sectionElement } from './dom/sectionElement';
import { blockquoteElement } from './dom/blockquoteElement';
import { ddElement } from './dom/ddElement';
import { dirElement } from './dom/dirElement';
import { divElement } from './dom/divElement';
import { dlElement } from './dom/dlElement';
import { dtElement } from './dom/dtElement';
import { figcaptionElement } from './dom/figcaptionElement';
import { figureElement } from './dom/figureElement';
import { hrElement } from './dom/hrElement';
import { liElement } from './dom/liElement';
import { olElement } from './dom/olElement';
import { pElement } from './dom/pElement';
import { preElement } from './dom/preElement';
import { ulElement } from './dom/ulElement';
import { aElement } from './dom/aElement';
import { abbrElement } from './dom/abbrElement';
import { bElement } from './dom/bElement';
import { bdiElement } from './dom/bdiElement';
import { bdoElement } from './dom/bdoElement';
import { brElement } from './dom/brElement';
import { citeElement } from './dom/citeElement';
import { codeElement } from './dom/codeElement';
import { dataElement } from './dom/dataElement';
import { dfnElement } from './dom/dfnElement';
import { emElement } from './dom/emElement';
import { iElement } from './dom/iElement';
import { kbdElement } from './dom/kbdElement';
import { markElement } from './dom/markElement';
import { qElement } from './dom/qElement';
import { rbElement } from './dom/rbElement';
import { rpElement } from './dom/rpElement';
import { rtElement } from './dom/rtElement';
import { rtcElement } from './dom/rtcElement';
import { rubyElement } from './dom/rubyElement';
import { sElement } from './dom/sElement';
import { sampElement } from './dom/sampElement';
import { smallElement } from './dom/smallElement';
import { spanElement } from './dom/spanElement';
import { strongElement } from './dom/strongElement';
import { subElement } from './dom/subElement';
import { supElement } from './dom/supElement';
import { timeElement } from './dom/timeElement';
import { ttElement } from './dom/ttElement';
import { uElement } from './dom/uElement';
import { varElement } from './dom/varElement';
import { wbrElement } from './dom/wbrElement';
import { areaElement } from './dom/areaElement';
import { audioElement } from './dom/audioElement';
import { imgElement } from './dom/imgElement';
import { mapElement } from './dom/mapElement';
import { trackElement } from './dom/trackElement';
import { videoElement } from './dom/videoElement';
import { appletElement } from './dom/appletElement';
import { embedElement } from './dom/embedElement';
import { iframeElement } from './dom/iframeElement';
import { noembedElement } from './dom/noembedElement';
import { objectElement } from './dom/objectElement';
import { paramElement } from './dom/paramElement';
import { pictureElement } from './dom/pictureElement';
import { sourceElement } from './dom/sourceElement';
import { canvasElement } from './dom/canvasElement';
import { noscriptElement } from './dom/noscriptElement';
import { scriptElement } from './dom/scriptElement';
import { delElement } from './dom/delElement';
import { insElement } from './dom/insElement';
import { captionElement } from './dom/captionElement';
import { colElement } from './dom/colElement';
import { colgroupElement } from './dom/colgroupElement';
import { tableElement } from './dom/tableElement';
import { tbodyElement } from './dom/tbodyElement';
import { tdElement } from './dom/tdElement';
import { tfootElement } from './dom/tfootElement';
import { thElement } from './dom/thElement';
import { theadElement } from './dom/theadElement';
import { trElement } from './dom/trElement';
import { buttonElement } from './dom/buttonElement';
import { datalistElement } from './dom/datalistElement';
import { fieldsetElement } from './dom/fieldsetElement';
import { formElement } from './dom/formElement';
import { inputElement } from './dom/inputElement';
import { labelElement } from './dom/labelElement';
import { legendElement } from './dom/legendElement';
import { meterElement } from './dom/meterElement';
import { optgroupElement } from './dom/optgroupElement';
import { optionElement } from './dom/optionElement';
import { outputElement } from './dom/outputElement';
import { progressElement } from './dom/progressElement';
import { selectElement } from './dom/selectElement';
import { textareaElement } from './dom/textareaElement';
import { detailsElement } from './dom/detailsElement';
import { dialogElement } from './dom/dialogElement';
import { menuElement } from './dom/menuElement';
import { menuitemElement } from './dom/menuitemElement';
import { summaryElement } from './dom/summaryElement';
import { contentElement } from './dom/contentElement';
import { elementElement } from './dom/elementElement';
import { shadowElement } from './dom/shadowElement';
import { slotElement } from './dom/slotElement';
import { templateElement } from './dom/templateElement';

declare global {
  namespace plusnew {
    namespace JSX {
      /**
       * the JSX.Element is a abstract representation of a Component
       */
      interface Element extends PlusnewAbstractElement {}

      interface ElementChildrenAttribute {
        // @FIXME children are always arrays, but typescript doesn't accept that because of react
        children: {};
      }

      /**
       * All the DOM Nodes are here
       */
      interface IntrinsicElements {
        html: htmlElement;
        link: linkElement;
        meta: metaElement;
        style: styleElement;
        title: titleElement;
        body: bodyElement;
        head: headElement;
        address: addressElement;
        article: articleElement;
        aside: asideElement;
        footer: footerElement;
        header: headerElement;
        h1: h1Element;
        h2: h2Element;
        h3: h3Element;
        h4: h4Element;
        h5: h5Element;
        h6: h6Element;
        hgroup: hgroupElement;
        main: mainElement;
        nav: navElement;
        section: sectionElement;
        blockquote: blockquoteElement;
        dd: ddElement;
        dir: dirElement;
        div: divElement;
        dl: dlElement;
        dt: dtElement;
        figcaption: figcaptionElement;
        figure: figureElement;
        hr: hrElement;
        li: liElement;
        ol: olElement;
        p: pElement;
        pre: preElement;
        ul: ulElement;
        a: aElement;
        abbr: abbrElement;
        b: bElement;
        bdi: bdiElement;
        bdo: bdoElement;
        br: brElement;
        cite: citeElement;
        code: codeElement;
        data: dataElement;
        dfn: dfnElement;
        em: emElement;
        i: iElement;
        kbd: kbdElement;
        mark: markElement;
        q: qElement;
        rb: rbElement;
        rp: rpElement;
        rt: rtElement;
        rtc: rtcElement;
        ruby: rubyElement;
        s: sElement;
        samp: sampElement;
        small: smallElement;
        span: spanElement;
        strong: strongElement;
        sub: subElement;
        sup: supElement;
        time: timeElement;
        tt: ttElement;
        u: uElement;
        var: varElement;
        wbr: wbrElement;
        area: areaElement;
        audio: audioElement;
        img: imgElement;
        map: mapElement;
        track: trackElement;
        video: videoElement;
        applet: appletElement;
        embed: embedElement;
        iframe: iframeElement;
        noembed: noembedElement;
        object: objectElement;
        param: paramElement;
        picture: pictureElement;
        source: sourceElement;
        canvas: canvasElement;
        noscript: noscriptElement;
        script: scriptElement;
        del: delElement;
        ins: insElement;
        caption: captionElement;
        col: colElement;
        colgroup: colgroupElement;
        table: tableElement;
        tbody: tbodyElement;
        td: tdElement;
        tfoot: tfootElement;
        th: thElement;
        thead: theadElement;
        tr: trElement;
        button: buttonElement;
        datalist: datalistElement;
        fieldset: fieldsetElement;
        form: formElement;
        input: inputElement;
        label: labelElement;
        legend: legendElement;
        meter: meterElement;
        optgroup: optgroupElement;
        option: optionElement;
        output: outputElement;
        progress: progressElement;
        select: selectElement;
        textarea: textareaElement;
        details: detailsElement;
        dialog: dialogElement;
        menu: menuElement;
        menuitem: menuitemElement;
        summary: summaryElement;
        content: contentElement;
        element: elementElement;
        shadow: shadowElement;
        slot: slotElement;
        template: templateElement;
      }

      interface IntrinsicAttributes {
        key?: string | number;
      }
    }
  }
}
